import { Message } from 'discord.js';
import Commands from '../src/commands';
const commands = new Commands();

export default function commandsIndex(
  msg: Message,
  args: string[],
  raw_input: string
) {
  return {
    alias: {},
    aliases: {},
    andate: commands.leave(msg),
    leave: commands.leave(msg),
    tomatela: commands.leave(msg),
    shu: commands.leave(msg),
    chau: commands.leave(msg),
    clear: commands.clear_queue(msg),
    deletequeue: {},
    gracias: commands.gracias(msg),
    getlink: commands.find(msg, args, raw_input),
    find: commands.find(msg, args, raw_input),
    help: commands.display_help(msg),
    hola: commands.join(msg),
    veni: commands.join(msg),
    juernes: commands.juernes(msg),
    loop: commands.loop(msg),
    quesuena: commands.now_playing(msg),
    mood: commands.mood(msg, args),
    mute: commands.mute(),
    playi: commands.playI(msg, args),
    jump: commands.jump(msg, args),
    previaycachengue: commands.previa_y_cachengue(msg, args),
    prefix: commands.change_prefix(msg, args),
    showprefix: {},
    status: commands.status(msg),
    stop: commands.stop(msg),
    queue: commands.display_queue(msg),
    q: commands.display_queue(msg),
    queues: {},
    random: {},
    resume: commands.resume(msg),
    skip: commands.next(msg),
    n: commands.next(msg),
    next: commands.next(msg),
    satura: commands.satura(msg),
    spam: commands.spam(msg, args),
    shuffle: commands.shuffle_queue(msg),
    sq: {},
    test: {},
    unmute: commands.unmute(),
    vs: commands.volume_set(msg, args),
    volumeset: commands.volume_set(msg, args),
    wendia: commands.wendia(msg),
  };
}
